version: "3.1"
services:
  mongodb:
    image: mongo:5.0
    restart: always
    container_name: "ChatDB"
    environment:
      MONGO_INITDB_ROOT_USERNAME: USERNAME
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
    ports:
      - 27017:27017
    networks:
      - chatnetwork
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
  chatapp:
    container_name: "ChatApp"
    build: .
    environment:
      SERVER_HOST: "0.0.0.0"
      SERVER_PORT: "5000"
      PUBLIC_HOST: "0.0.0.0:5000"
      TLS: ""
      JWT_SECRET: "JWT-SECRET-STRING"
      MONGO_URI: "mongodb://USERNAME:PASSWORD@mongodb:27017"
      MONGO_DATABASE: "DATABASE_NAME"
    ports:
      - 5000:5000
    depends_on:
      - mongodb
    networks:
      - chatnetwork
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'

networks:
  chatnetwork:
    driver: bridge