version: "3.1"
services:
  mongodb:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: DATABASE_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: DATABASE_PASSWORD
    ports:
      - 27017:27017
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'